/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/v1/boletas/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Receipt Page */
        get: operations["public_receipt_page_public_v1_boletas__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/v1/boletas/{public_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Receipt Pdf */
        get: operations["public_receipt_pdf_public_v1_boletas__public_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-deliveries/{delivery_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fiscal Delivery */
        get: operations["get_fiscal_delivery_v1_fiscal_deliveries__delivery_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-document-drafts/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Fiscal Draft */
        post: operations["validate_fiscal_draft_v1_fiscal_document_drafts_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_v1_fiscal_documents_get"];
        put?: never;
        /** Issue Document */
        post: operations["issue_document_v1_fiscal_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_v1_fiscal_documents__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents/{record_id}/annulment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Annul Fiscal Document */
        post: operations["annul_fiscal_document_v1_fiscal_documents__record_id__annulment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents/{record_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Amount Correction */
        post: operations["issue_amount_correction_v1_fiscal_documents__record_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents/{record_id}/corrections/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Fiscal Document Text */
        post: operations["correct_fiscal_document_text_v1_fiscal_documents__record_id__corrections_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents/{record_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Invoice Delivery */
        post: operations["queue_invoice_delivery_v1_fiscal_documents__record_id__deliveries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents/{record_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Events */
        get: operations["get_document_events_v1_fiscal_documents__record_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents/{record_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Pdf */
        get: operations["get_document_pdf_v1_fiscal_documents__record_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-documents/{record_id}/xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Xml */
        get: operations["get_document_xml_v1_fiscal_documents__record_id__xml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fiscal-envelopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fiscal Envelopes */
        get: operations["list_fiscal_envelopes_v1_fiscal_envelopes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operational-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operational Alerts */
        get: operations["operational_alerts_v1_operational_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rcv/purchases/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Rcv Snapshot */
        post: operations["import_rcv_snapshot_v1_rcv_purchases_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rcv/purchases/{year}/{month}/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reconcile Rcv Snapshot */
        get: operations["reconcile_rcv_snapshot_v1_rcv_purchases__year___month__reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/received-classifications/{classification_id}/line-allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Allocate Received Lines */
        post: operations["allocate_received_lines_v1_received_classifications__classification_id__line_allocations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/received-decisions/{decision_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile Received Decision */
        post: operations["reconcile_received_decision_v1_received_decisions__decision_id__reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/received-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Received Documents */
        get: operations["list_received_documents_v1_received_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/received-documents/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Received Document */
        post: operations["import_received_document_v1_received_documents_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/received-documents/{record_id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Received Classification */
        get: operations["get_received_classification_v1_received_documents__record_id__classification_get"];
        put?: never;
        /** Classify Received Document */
        post: operations["classify_received_document_v1_received_documents__record_id__classification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/received-documents/{record_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Received Document */
        post: operations["decide_received_document_v1_received_documents__record_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/monthly/{year}/{month}.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Monthly Csv */
        get: operations["export_monthly_csv_v1_reports_monthly__year___month__csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/monthly/{year}/{month}.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Monthly Pdf */
        get: operations["export_monthly_pdf_v1_reports_monthly__year___month__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/monthly/{year}/{month}.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Monthly Xlsx */
        get: operations["export_monthly_xlsx_v1_reports_monthly__year___month__xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/monthly/{year}/{month}/accountant-package.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Accountant Package */
        get: operations["export_accountant_package_v1_reports_monthly__year___month__accountant_package_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnulmentRequest */
        AnnulmentRequest: {
            /**
             * Issued On
             * Format: date
             */
            issued_on: string;
        };
        /**
         * CorrectionCode
         * @enum {integer}
         */
        CorrectionCode: 1 | 2 | 3;
        /** CorrectionIssueRequest */
        CorrectionIssueRequest: {
            document_type: components["schemas"]["DocumentType"];
            /**
             * Issued On
             * Format: date
             */
            issued_on: string;
            issuer: components["schemas"]["IssuerRequest"];
            /** Lines */
            lines: components["schemas"]["FiscalLineRequest"][];
            /** Reason */
            reason: string;
        };
        /** DeliveryRequest */
        DeliveryRequest: {
            /** Recipient Email */
            recipient_email?: string | null;
        };
        /** DeliveryResponse */
        DeliveryResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Created At */
            created_at: string;
            /** Document Record Id */
            document_record_id: string;
            /** Error Message */
            error_message: string | null;
            /** Exchange Xml Sha256 */
            exchange_xml_sha256: string;
            /** Id */
            id: string;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /** Provider Id */
            provider_id: string | null;
            /** Recipient Email */
            recipient_email: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * DispatchAccount
         * @description Quién soporta el despacho según ``TipoDespacho`` del SII.
         * @enum {integer}
         */
        DispatchAccount: 1 | 2 | 3;
        /**
         * DispatchReason
         * @enum {integer}
         */
        DispatchReason: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
        /** DispatchTransportRequest */
        DispatchTransportRequest: {
            /** Carrier Rut */
            carrier_rut?: string | null;
            /** Destination Address */
            destination_address?: string | null;
            /** Destination City */
            destination_city?: string | null;
            /** Destination Commune */
            destination_commune?: string | null;
            /** Driver Name */
            driver_name?: string | null;
            /** Driver Rut */
            driver_rut?: string | null;
            /** Vehicle Plate */
            vehicle_plate?: string | null;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Counterparty Name */
            counterparty_name: string;
            /** Created At */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** Document Type */
            document_type: number;
            /** Folio */
            folio: number;
            /** Id */
            id: string;
            /** Issued On */
            issued_on: string;
            /** Public Url */
            public_url: string;
            /** Status */
            status: string;
            /** Taxpayer Rut */
            taxpayer_rut: string;
            /** Total */
            total: number;
            /** Xml Sha256 */
            xml_sha256: string;
            /** Xml Url */
            xml_url: string;
        };
        /**
         * DocumentType
         * @enum {integer}
         */
        DocumentType: 33 | 34 | 39 | 41 | 52 | 56 | 61;
        /** DraftValidationResponse */
        DraftValidationResponse: {
            /** Builder Status */
            builder_status: string;
            /** Document Name */
            document_name: string;
            /** Document Type */
            document_type: number;
            /** Line Count */
            line_count: number;
            /** Receiver Required */
            receiver_required: boolean;
            /** Valid */
            valid: boolean;
        };
        /** EnvelopeResponse */
        EnvelopeResponse: {
            /** Created At */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Taxpayer Rut */
            taxpayer_rut: string;
            /** Track Id */
            track_id: string | null;
            /** Updated At */
            updated_at: string;
            /** Xml Sha256 */
            xml_sha256: string;
        };
        /** EventResponse */
        EventResponse: {
            /** Event Type */
            event_type: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Occurred At */
            occurred_at: string;
            /** Sequence */
            sequence: number;
        };
        /** FiscalDraftRequest */
        FiscalDraftRequest: {
            /** Branch Id */
            branch_id: string;
            /**
             * Currency
             * @default CLP
             */
            currency: string;
            dispatch_reason?: components["schemas"]["DispatchReason"] | null;
            document_type: components["schemas"]["DocumentType"];
            /** Due On */
            due_on?: string | null;
            /**
             * Issued On
             * Format: date
             */
            issued_on: string;
            /** Issuer Profile Id */
            issuer_profile_id: string;
            /** Lines */
            lines: components["schemas"]["FiscalLineRequest"][];
            payment_method?: components["schemas"]["PaymentMethod"] | null;
            payment_terms?: components["schemas"]["PaymentTerms"] | null;
            receiver?: components["schemas"]["PartyRequest"] | null;
            /**
             * References
             * @default []
             */
            references: components["schemas"]["FiscalReferenceRequest"][];
        };
        /** FiscalLineRequest */
        FiscalLineRequest: {
            /** Description */
            description?: string | null;
            /**
             * Discount Amount
             * @default 0
             */
            discount_amount: number | string;
            /**
             * Discount Percent
             * @default 0
             */
            discount_percent: number | string;
            /** Name */
            name: string;
            price_mode: components["schemas"]["PriceMode"];
            /** Quantity */
            quantity: number | string;
            /**
             * Surcharge Amount
             * @default 0
             */
            surcharge_amount: number | string;
            /**
             * Surcharge Percent
             * @default 0
             */
            surcharge_percent: number | string;
            tax_category: components["schemas"]["TaxCategory"];
            /** Unit Measure */
            unit_measure?: string | null;
            /** Unit Price */
            unit_price: number | string;
        };
        /** FiscalReferenceRequest */
        FiscalReferenceRequest: {
            correction_code?: components["schemas"]["CorrectionCode"] | null;
            /** Document Type */
            document_type: string;
            /** Folio */
            folio?: string | null;
            /** Issued On */
            issued_on?: string | null;
            /** Line Number */
            line_number: number;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IssueRequest */
        IssueRequest: {
            /**
             * Branch Id
             * @default main
             */
            branch_id: string;
            dispatch_account?: components["schemas"]["DispatchAccount"] | null;
            dispatch_reason?: components["schemas"]["DispatchReason"] | null;
            /** @default 39 */
            document_type: components["schemas"]["DocumentType"];
            /** Due On */
            due_on?: string | null;
            /**
             * Issued On
             * Format: date
             */
            issued_on: string;
            issuer: components["schemas"]["IssuerRequest"];
            /**
             * Issuer Profile Id
             * @default default
             */
            issuer_profile_id: string;
            /** Lines */
            lines: (components["schemas"]["LineRequest"] | components["schemas"]["FiscalLineRequest"])[];
            payment_terms?: components["schemas"]["PaymentTerms"] | null;
            receiver?: components["schemas"]["PartyRequest"] | null;
            /**
             * Receiver Name
             * @default SIN INFORMACION
             */
            receiver_name: string;
            /**
             * Receiver Rut
             * @default 66666666-6
             */
            receiver_rut: string;
            reference?: components["schemas"]["ReferenceRequest"] | null;
            transport?: components["schemas"]["DispatchTransportRequest"] | null;
        };
        /** IssuerRequest */
        IssuerRequest: {
            /** Activity Code */
            activity_code: number;
            /** Address */
            address?: string | null;
            /** Business Activity */
            business_activity: string;
            /** Commune */
            commune?: string | null;
            /** Legal Name */
            legal_name: string;
            /** Rut */
            rut: string;
        };
        /** LineRequest */
        LineRequest: {
            /**
             * Discount Gross
             * @default 0
             */
            discount_gross: number | string;
            /**
             * Is Exempt
             * @default false
             */
            is_exempt: boolean;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | string;
            /** Unit Measure */
            unit_measure?: string | null;
            /** Unit Price Gross */
            unit_price_gross: number | string;
        };
        /** OperationalAlertResponse */
        OperationalAlertResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Resource Id */
            resource_id: string | null;
            /** Severity */
            severity: string;
        };
        /** PartyRequest */
        PartyRequest: {
            /** Address */
            address?: string | null;
            /** Business Activity */
            business_activity?: string | null;
            /** City */
            city?: string | null;
            /** Commune */
            commune?: string | null;
            /** Email */
            email?: string | null;
            /** Legal Name */
            legal_name: string;
            /** Phone */
            phone?: string | null;
            /** Rut */
            rut: string;
        };
        /**
         * PaymentMethod
         * @enum {integer}
         */
        PaymentMethod: 1 | 2 | 3 | 4 | 5;
        /**
         * PaymentTerms
         * @enum {integer}
         */
        PaymentTerms: 1 | 2 | 3;
        /**
         * PriceMode
         * @enum {string}
         */
        PriceMode: "gross" | "net";
        /** PurchaseAllocationsRequest */
        PurchaseAllocationsRequest: {
            /** Allocations */
            allocations: components["schemas"]["PurchaseLineAllocationRequest"][];
        };
        /**
         * PurchaseDestination
         * @enum {string}
         */
        PurchaseDestination: "expense" | "inventory" | "fixed_asset";
        /** PurchaseLineAllocationRequest */
        PurchaseLineAllocationRequest: {
            /** Control Plane Ref */
            control_plane_ref?: string | null;
            destination: components["schemas"]["PurchaseDestination"];
            /** Line Number */
            line_number: number;
        };
        /** RcvDifferenceResponse */
        RcvDifferenceResponse: {
            /** Document Type */
            document_type: number;
            /** Folio */
            folio: number;
            /** Issuer Rut */
            issuer_rut: string;
            /** Kind */
            kind: string;
            /** Rcv Total */
            rcv_total: number | null;
            /** Xml Total */
            xml_total: number | null;
        };
        /** RcvEntryRequest */
        RcvEntryRequest: {
            document_type: components["schemas"]["DocumentType"];
            /** Exempt Amount */
            exempt_amount: number;
            /** Folio */
            folio: number;
            /**
             * Issued On
             * Format: date
             */
            issued_on: string;
            /** Issuer Rut */
            issuer_rut: string;
            /** Net Amount */
            net_amount: number;
            status: components["schemas"]["RcvPurchaseStatus"];
            /** Total Amount */
            total_amount: number;
            /** Vat Amount */
            vat_amount: number;
        };
        /** RcvImportRequest */
        RcvImportRequest: {
            /** Entries */
            entries: components["schemas"]["RcvEntryRequest"][];
            /** Month */
            month: number;
            /** Source */
            source: string;
            /** Year */
            year: number;
        };
        /**
         * RcvPurchaseStatus
         * @enum {string}
         */
        RcvPurchaseStatus: "pending" | "registered" | "claimed" | "excluded";
        /** RcvSnapshotResponse */
        RcvSnapshotResponse: {
            /** Id */
            id: string;
            /** Imported At */
            imported_at: string;
            /** Payload Sha256 */
            payload_sha256: string;
            /** Period */
            period: string;
            /** Source */
            source: string;
            /** Version */
            version: number;
        };
        /** ReceivedClassificationRequest */
        ReceivedClassificationRequest: {
            /** Category Code */
            category_code?: string | null;
            /** Destination */
            destination: string;
            /** Notes */
            notes?: string | null;
            /** Provider Id */
            provider_id?: string | null;
        };
        /** ReceivedClassificationResponse */
        ReceivedClassificationResponse: {
            /** Category Code */
            category_code: string | null;
            /** Classified By */
            classified_by: string;
            /** Created At */
            created_at: string;
            /** Destination */
            destination: string;
            /** Id */
            id: string;
            /** Notes */
            notes: string | null;
            /** Provider Id */
            provider_id: string | null;
            /** Received Document Id */
            received_document_id: string;
            /** Version */
            version: number;
        };
        /** ReceivedDecisionRequest */
        ReceivedDecisionRequest: {
            decision: components["schemas"]["ReceivedDecisionType"];
            /** Reason */
            reason?: string | null;
        };
        /** ReceivedDecisionResponse */
        ReceivedDecisionResponse: {
            /** Created At */
            created_at: string;
            /** Decision */
            decision: string;
            /** Id */
            id: string;
            /** Reason */
            reason: string | null;
            /** Received Document Id */
            received_document_id: string;
            /** Remote Code */
            remote_code: string | null;
            /** Remote Message */
            remote_message: string | null;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * ReceivedDecisionType
         * @enum {string}
         */
        ReceivedDecisionType: "accept_content" | "ack_receipt" | "claim_content" | "claim_partial_delivery" | "claim_total_delivery";
        /** ReceivedDocumentResponse */
        ReceivedDocumentResponse: {
            /** Document Type */
            document_type: number;
            /** Folio */
            folio: number;
            /** Id */
            id: string;
            /** Issued On */
            issued_on: string;
            /** Issuer Name */
            issuer_name: string;
            /** Issuer Rut */
            issuer_rut: string;
            /** Received At */
            received_at: string;
            /** Sii Received At */
            sii_received_at: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Total */
            total: number;
            /** Xml Sha256 */
            xml_sha256: string;
        };
        /** ReferenceRequest */
        ReferenceRequest: {
            /** Code */
            code: string;
            /** Reason */
            reason: string;
        };
        /**
         * TaxCategory
         * @enum {string}
         */
        TaxCategory: "affected" | "exempt" | "non_billable";
        /** TextCorrectionRequest */
        TextCorrectionRequest: {
            /** Address */
            address: string;
            /** Business Activity */
            business_activity: string;
            /** Commune */
            commune: string;
            /**
             * Issued On
             * Format: date
             */
            issued_on: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    public_receipt_page_public_v1_boletas__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_receipt_pdf_public_v1_boletas__public_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fiscal_delivery_v1_fiscal_deliveries__delivery_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_fiscal_draft_v1_fiscal_document_drafts_validate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FiscalDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_fiscal_documents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_document_v1_fiscal_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_fiscal_documents__record_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annul_fiscal_document_v1_fiscal_documents__record_id__annulment_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnulmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_amount_correction_v1_fiscal_documents__record_id__corrections_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionIssueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_fiscal_document_text_v1_fiscal_documents__record_id__corrections_text_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_invoice_delivery_v1_fiscal_documents__record_id__deliveries_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_events_v1_fiscal_documents__record_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_pdf_v1_fiscal_documents__record_id__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_xml_v1_fiscal_documents__record_id__xml_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fiscal_envelopes_v1_fiscal_envelopes_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operational_alerts_v1_operational_alerts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationalAlertResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_rcv_snapshot_v1_rcv_purchases_snapshots_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RcvImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RcvSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_rcv_snapshot_v1_rcv_purchases__year___month__reconciliation_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RcvDifferenceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    allocate_received_lines_v1_received_classifications__classification_id__line_allocations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                classification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseAllocationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_received_decision_v1_received_decisions__decision_id__reconcile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivedDecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_received_documents_v1_received_documents_get: {
        parameters: {
            query?: {
                document_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivedDocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_received_document_v1_received_documents_import_post: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivedDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_received_classification_v1_received_documents__record_id__classification_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivedClassificationResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_received_document_v1_received_documents__record_id__classification_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceivedClassificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivedClassificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_received_document_v1_received_documents__record_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceivedDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivedDecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_monthly_csv_v1_reports_monthly__year___month__csv_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_monthly_pdf_v1_reports_monthly__year___month__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_monthly_xlsx_v1_reports_monthly__year___month__xlsx_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_accountant_package_v1_reports_monthly__year___month__accountant_package_zip_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
