"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft,CheckCircle2,Info } from "lucide-react";

export function CommercialWizard({kind}:{kind:"quote"|"purchase_order"}){
 const sales=kind==="quote";const [name,setName]=useState("");const [description,setDescription]=useState("");const [amount,setAmount]=useState(0);const [saved,setSaved]=useState<"engine"|"demo"|null>(null);const [error,setError]=useState("");
 async function submit(event:React.FormEvent){event.preventDefault();setError("");const payload={kind,branch_id:"main",counterparty_ref:`manual:${name.toLowerCase()}`,counterparty_name:name,issued_on:new Date().toISOString().slice(0,10),valid_until:sales?new Date(Date.now()+15*86400000).toISOString().slice(0,10):null,currency:"CLP",notes:"",lines:[{description,quantity:"1",unit_price:String(amount),discount_percent:"0"}]};
  try{const response=await fetch("/api/commercial-documents",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(payload)});if(response.ok){setSaved("engine");return}if(response.status!==503)throw new Error((await response.json()).detail??"No fue posible guardar");sessionStorage.setItem(`completo-fiscal:${kind}:${Date.now()}`,JSON.stringify(payload));setSaved("demo")}catch(e){setError(e instanceof Error?e.message:"No fue posible guardar")}}
 return <div className="page section-page wizard-page"><Link className="back-link" href={sales?"/ventas":"/compras"}><ArrowLeft size={15}/> Volver</Link><header className="page-header"><div><p className="eyebrow">{sales?"Ciclo comercial":"Abastecimiento"}</p><h1>{sales?"Nueva cotización":"Nueva orden de compra"}</h1><p>{sales?"Prepara una propuesta sin consumir folios SII.":"Deja monto y proveedor listos para aprobación."}</p></div></header><div className="wizard-grid"><form className="panel wizard-form" onSubmit={submit}><label>{sales?"Cliente":"Proveedor"}<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Producto o servicio<input required value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Monto total CLP<input required min="1" type="number" value={amount||""} onChange={e=>setAmount(Number(e.target.value))}/></label><button className="primary-button" type="submit">Guardar borrador</button>{error&&<p className="form-error">{error}</p>}{saved&&<div className="validation-success" role="status"><CheckCircle2 size={18}/><div><strong>Borrador guardado</strong><p>{saved==="engine"?"Persistido en el motor fiscal.":"Guardado sólo en este navegador porque el motor no está conectado."}</p></div></div>}</form><aside className="panel tax-preview"><Info size={20}/><h2>No es un DTE</h2><p>Podrás enviarlo, aprobarlo y convertirlo después. Recién la conversión tributaria firma y consume folio.</p></aside></div></div>
}
