import Link from "next/link";
import { AlertTriangle, CheckCircle2, Clock3, FileCheck2, Filter, Search } from "lucide-react";

const received = [
  { id: "demo-33-7841", type: 33, folio: 7841, issuer: "DISTRIBUIDORA CENTRAL SPA", rut: "76.345.210-8", date: "10 jul 2026", total: "$428.400", status: "Por revisar", tone: "warning" },
  { id: "demo-34-391", type: 34, folio: 391, issuer: "SERVICIOS FRÍO SUR LTDA.", rut: "77.120.934-2", date: "9 jul 2026", total: "$85.000", status: "Aceptado", tone: "success" },
  { id: "demo-61-88", type: 61, folio: 88, issuer: "DISTRIBUIDORA CENTRAL SPA", rut: "76.345.210-8", date: "8 jul 2026", total: "$23.800", status: "Por asociar", tone: "neutral" },
];

export function ReceivedInbox() {
  return <div className="page section-page"><header className="page-header"><div><p className="eyebrow">Compras y recepción fiscal</p><h1>Documentos recibidos</h1><p>XML validados contra firma, esquema y RUT antes de entrar a tu operación.</p></div><button className="primary-button" type="button"><FileCheck2 size={17} /> Importar XML</button></header><div className="summary-grid"><article className="panel summary-card"><Clock3 size={19} /><div><small>Requieren revisión</small><strong>1</strong><p>Antes de aceptar o reclamar</p></div></article><article className="panel summary-card"><CheckCircle2 size={19} /><div><small>Aceptados este mes</small><strong>18</strong><p>$4.281.900 documentados</p></div></article><article className="panel summary-card"><AlertTriangle size={19} /><div><small>Diferencias RCV</small><strong>0</strong><p>Sin discrepancias detectadas</p></div></article></div><section className="panel documents-panel"><div className="table-toolbar"><div><h2>Bandeja tributaria</h2><p>Modo demostración · datos sintéticos</p></div><div><button className="secondary-button" type="button"><Search size={15} /> Buscar</button><button className="secondary-button" type="button"><Filter size={15} /> Filtrar</button></div></div><div className="received-list">{received.map((item) => <article className="received-row" key={item.id}><span className="document-code">{item.type}</span><div className="received-main"><strong>{item.issuer}</strong><p>{item.rut} · Folio {item.folio} · {item.date}</p></div><strong className="received-total">{item.total}</strong><span className={`received-status ${item.tone}`}>{item.status}</span><Link className="secondary-button" href={`/recibidos/${item.id}`}>Revisar</Link></article>)}</div></section><section className="tip-card"><FileCheck2 size={21} /><div><strong>El PDF no reemplaza al XML</strong><p>OCR puede ayudar a clasificar una compra, pero las decisiones tributarias se basan siempre en el XML firmado.</p></div></section></div>;
}
