import { AlertTriangle, ArrowRight, Building2, CheckCircle2, CloudCog, FileChartColumn, Landmark, ReceiptText, RefreshCw, Scale, ShieldCheck } from "lucide-react";
import { clp } from "@/lib/format";
import { bheRows, f29Lines, rcvDocuments, syncRows } from "@/lib/sii-demo-data";
import type { EngineSectionResult } from "@/lib/fiscal-api";
import { DemoActionButton } from "./demo-action-button";

function SourceBar({ version = "snapshot sintético v2" }: { version?: string }) {
  return <div className="sii-source"><span><CloudCog size={15} /><strong>Vista SII</strong> {version}</span><span>Consultado 11 jul 2026 · 08:20</span></div>;
}

export function RcvSection() {
  return <div className="page section-page"><SiiHeader eyebrow="Registro tributario" title="Compras y ventas ante el SII" detail="Una vista única para distinguir datos propios, datos consultados y diferencias." action="Sincronizar período" /><SourceBar version="snapshot sintético v3" /><div className="summary-grid"><Metric label="Ventas informadas" value="$1.218.990" detail="48 boletas · 1 período" /><Metric label="Compras informadas" value="$632.400" detail="3 documentos" /><Metric label="Diferencias" value="1" detail="Factura sin XML recibido" warning /></div><section className="panel sii-table"><div className="table-toolbar"><div><h2>Julio 2026</h2><p>Comparación semántica por RUT, tipo, folio y monto</p></div><span className="demo-action">Datos sanitizados</span></div><div className="sii-table-head"><span>Origen</span><span>Documento</span><span>Contraparte</span><span>Neto</span><span>IVA</span><span>Total</span><span>Resultado</span></div>{rcvDocuments.map((row) => <article key={`${row.direction}-${row.type}-${row.folio}`}><strong>{row.direction}</strong><span>DTE {row.type} · {row.folio}</span><span>{row.party}</span><span>{clp(row.net)}</span><span>{clp(row.vat)}</span><strong>{clp(row.total)}</strong><em className={row.match === "Coincide" ? "ok" : "warning"}>{row.match}</em></article>)}</section><DifferenceTip /></div>;
}

type CloseList = Array<{ payload: { total_payable: number; sales: { vat: number }; purchases: { vat: number }; lines: Array<{ code: string; label: string; amount: number; sii_amount: number | null; state: string }> } }>;
export function F29Section({ result }: { result: EngineSectionResult<CloseList> }) {
  const close = result.data?.[0]?.payload;
  const fallback = result.source === "demo";
  const payable = close?.total_payable ?? (fallback ? 157492 : 0);
  const lines = close?.lines.filter(line => ["sales_vat", "purchase_vat", "second_category_withholding", "ppm"].includes(line.code)).map(line => ({ code: line.code, label: line.label, completo: line.amount, sii: line.sii_amount ?? line.amount })) ?? (fallback ? f29Lines : []);
  const debit = close?.sales.vat ?? (fallback ? 194629 : 0), credit = close?.purchases.vat ?? (fallback ? 68400 : 0);
  return <div className="page section-page"><SiiHeader eyebrow="Declaración mensual" title="Propuesta F29 · julio 2026" detail="Completo explica la composición; la presentación sigue realizándose en el SII." action="Actualizar propuesta" /><SourceBar version={result.source === "engine" ? "cálculo del motor" : "snapshot sintético v2"} /><div className="summary-grid"><Metric label="Débito fiscal" value={clp(debit)} detail="Desde ventas del período" /><Metric label="Crédito fiscal" value={clp(credit)} detail="Compras respaldadas" /><Metric label="Pago estimado" value={clp(payable)} detail="Informativo · no declarado" /></div><div className="f29-layout"><section className="panel f29-lines"><div className="table-toolbar"><div><h2>Conciliación por código</h2><p>Cálculo Completo frente a propuesta consultada</p></div><span className="received-status success">Sin diferencias</span></div>{lines.map((line) => <article key={line.code}><span><small>{line.code}</small><strong>{line.label}</strong></span><span><small>Completo</small>{clp(line.completo)}</span><span><small>SII</small>{clp(line.sii)}</span><CheckCircle2 size={17} /></article>)}</section><aside className="panel tax-explanation"><Scale size={25} /><p className="eyebrow">Cómo se forma</p><h2>{clp(payable)}</h2><p>Débito menos crédito, más retenciones y PPM del período.</p><dl><div><dt>IVA ventas</dt><dd>+{clp(debit)}</dd></div><div><dt>IVA compras</dt><dd>−{clp(credit)}</dd></div></dl><div className="legal-warning"><AlertTriangle size={17} /><p>No es una declaración presentada ni una orden de pago.</p></div></aside></div></div>;
}

export function BheSection() {
  return <div className="page section-page"><SiiHeader eyebrow="Honorarios" title="Boletas emitidas y recibidas" detail="Retenciones visibles para Personas, Fiscal y revisión del F29." action="Consultar BHE" /><SourceBar /><div className="summary-grid"><Metric label="Bruto recibido" value="$45.000" detail="1 servicio contratado" /><Metric label="Retención por enterar" value="$6.863" detail="15,25% · julio 2026" /><Metric label="Bruto emitido" value="$120.000" detail="1 servicio prestado" /></div><section className="panel bhe-list"><div className="table-toolbar"><div><h2>Movimientos del período</h2><p>Montos en pesos chilenos, sin aproximaciones float</p></div></div>{bheRows.map((row) => <article key={`${row.direction}-${row.folio}`}><span className="document-code"><ReceiptText size={17} /></span><div><strong>{row.person}</strong><p>{row.direction} · Folio {row.folio} · {row.date}</p></div><div><small>Bruto</small><strong>{clp(row.gross)}</strong></div><div><small>Retención</small><strong>{clp(row.retention)}</strong></div><div><small>Líquido</small><strong>{clp(row.net)}</strong></div><em className="ok">{row.status}</em></article>)}</section></div>;
}

export function SiiProfileSection() {
  return <div className="page section-page"><SiiHeader eyebrow="Perfil tributario" title="Empresa Sintética Completo SpA" detail="Antecedentes consultados para reducir errores de onboarding y revisar cumplimiento." action="Actualizar perfil" /><SourceBar version="snapshot sintético v1" /><div className="profile-grid"><section className="panel profile-card"><Landmark size={23} /><p className="eyebrow">Contribuyente</p><h2>Primera categoría</h2><dl><div><dt>RUT</dt><dd>76.192.083-9</dd></div><div><dt>Régimen</dt><dd>Pro Pyme General</dd></div><div><dt>Inicio de actividades</dt><dd>15 marzo 2026</dd></div><div><dt>Estado</dt><dd><em className="ok">Vigente</em></dd></div></dl></section><section className="panel profile-card"><Building2 size={23} /><p className="eyebrow">Actividad principal</p><h2>Desarrollo de software</h2><dl><div><dt>Código</dt><dd>620200</dd></div><div><dt>Sucursal tributaria</dt><dd>Casa matriz</dd></div><div><dt>Dirección</dt><dd>Dirección sintética · Santiago</dd></div></dl></section><section className="panel declarations-card"><div className="table-toolbar"><div><h2>Declaraciones y eventos</h2><p>Sólo lectura · no permite presentar ni rectificar</p></div></div><article><span>F29</span><div><strong>Julio 2026 pendiente</strong><p>Propuesta disponible para revisión</p></div><ArrowRight size={17} /></article><article><span>F22</span><div><strong>Año tributario 2026</strong><p>Declaración recibida · sin observaciones</p></div><CheckCircle2 size={17} /></article></section></div></div>;
}

export function SyncSection() {
  return <div className="page section-page"><SiiHeader eyebrow="Conector de lectura" title="Sincronizaciones SII" detail="Cada consulta genera una versión nueva; jamás reescribe la evidencia anterior." action="Nueva sincronización" /><SourceBar version="worker simulado · sin credenciales" /><section className="panel sync-list"><div className="table-toolbar"><div><h2>Última ejecución</h2><p>Sesión cerrada correctamente · 11 jul 2026 08:20</p></div><span className="received-status success">Completada</span></div>{syncRows.map((row, index) => <article key={row.resource}><span>{index + 1}</span><div><strong>{row.resource}</strong><p>{row.at}</p></div><div><small>Resultado</small><strong>{row.result}</strong></div><code>{row.version}</code><em className={row.tone}>Correcto</em></article>)}</section><section className="tip-card"><ShieldCheck size={21} /><div><strong>El reader no puede emitir documentos</strong><p>Consulta y normaliza datos en un worker aislado; no accede a CAF, certificados ni firma tributaria.</p></div></section></div>;
}

function SiiHeader({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action: string }) { return <header className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{detail}</p></div><DemoActionButton area={`sii_${action.toLowerCase().replaceAll(" ", "_")}`} done="Snapshot simulado actualizado"><RefreshCw size={16} /> {action}</DemoActionButton></header>; }
function Metric({ label, value, detail, warning }: { label: string; value: string; detail: string; warning?: boolean }) { return <article className={`panel summary-card${warning ? " metric-warning" : ""}`}><FileChartColumn size={19} /><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></article>; }
function DifferenceTip() { return <section className="tip-card"><AlertTriangle size={21} /><div><strong>Una diferencia abre una tarea, no una corrección automática</strong><p>La factura que aparece sólo en el SII debe conseguirse o clasificarse antes de utilizarla tributariamente.</p></div></section>; }
